apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: podmi-ingress-controller-identity
  namespace: traefik
spec:
  type: 0
  resourceID: "/subscriptions/f75f6327-8759-4b37-87d4-b44bb79ba52b/resourceGroups/rg-ist-eastus-007/providers/Microsoft.ManagedIdentity/userAssignedIdentities/podmi-ingress-controller"
  clientID: da9497c2-30c1-46ca-9a56-61d10513bb67
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: podmi-ingress-controller-binding
  namespace: traefik
spec:
  azureIdentity: podmi-ingress-controller-identity
  selector: podmi-ingress-controller
